### ISSUE TITLE
Support for &bull;

### ISSUE THREAD

**Issue by wormeyman** [JamesParkNINJA/brackets-specRep#1]
I am hoping to add support for &bull; but i am running into trouble and i do not know what i am doing wrong!
- http://en.wikipedia.org/wiki/Bullet_%28typography%29
- http://www.fileformat.info/info/unicode/char/2022/index.htm

``` js
htmlContent = htmlContent.replace(/\u2022/g,"&bull;");
```

**Comment by JamesParkNINJA** [comment]
Whoa, apologies for the massive lapse in time, I didn't realise people would actually use this!

Did you figure this out?

If not I'll have a little look through the code again and see if I can work it.

**Comment by JamesParkNINJA** [comment]
Hmm.

I just tried it and it seems to work. Perhaps it's the source of the bullet? It may have a different type?

Try all three of these if you haven't already:

``` js
htmlContent = htmlContent.replace(/\u2022/g,"&bull;");
htmlContent = htmlContent.replace(/\u2219/g,"&bull;");
htmlContent = htmlContent.replace(/\u25E6/g,"&bull;");
```
